name: Deploy via Tailscale SSH

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Tailscale
        uses: tailscale/github-action@v2
        with:
          authkey: ${{ secrets.TAILSCALE_AUTHKEY }}

      - name: SSH deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: "100.117.249.28"             # Tailscale IP Twojej maszyny
          username: "daniel-wardak"
          port: 22
          key: ${{ secrets.SSH_PRIVATE_KEY }} # prywatny klucz, którego publiczna część jest w authorized_keys
          script: |
            set -euxo pipefail
            cd /home/daniel-wardak/ChatB2B
            git pull --ff-only
            sudo /usr/bin/systemctl restart chatbot.service
