name: Deploy Chatbot

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: "5.tcp.eu.ngrok.io"       # Zastąp tą wartością, jeśli Ngrok poda inny adres
          port: "19130"                   # Zastąp numerem portu z wyniku Ngrok
          username: "daniel-wardak"
          key: ${{ secrets.SERVER_SSH_KEY }}  # Klucz prywatny trzymany jako sekret (zalecane!)
          args: "-o StrictHostKeyChecking=no -o IdentitiesOnly=yes"
          script: |
            cd /home/daniel-wardak/ChatB2B
            git pull origin main
            sudo systemctl restart chatbot.service

