name: Deploy Chatbot

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}       # "4.tcp.eu.ngrok.io"
          port: ${{ secrets.SERVER_PORT }}       # "13637"
          username: daniel-wardak
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd /home/daniel-wardak/ChatB2B
            git pull origin main
            sudo systemctl restart chatbot.service

